# Generated by Django 4.2 on 2025-09-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Sudah Dibaca'),
        ),
    ]
