# Generated by Django 4.2 on 2025-09-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_notifikasi_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='fotofeedback',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/', verbose_name='Foto Feedback'),
        ),
        migrations.DeleteModel(
            name='Ulasan',
        ),
    ]
