# Generated by Django 4.2 on 2025-10-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_pelanggan_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tanggal Dibuat'),
        ),
    ]
