# Generated by Django 4.2 on 2025-09-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_transaksi_feedback_transaksi_fotofeedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='status_transaksi',
            field=models.CharField(choices=[('DIPROSES', 'Diproses'), ('DIBAYAR', 'Dibayar'), ('DIKIRIM', 'Dikirim'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='DIPROSES', max_length=50, verbose_name='Status Transaksi'),
        ),
    ]
