# Generated by Django 4.2 on 2025-10-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_pelanggan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='keterangan_diskon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='total_diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
