# Generated by Django 4.2 on 2025-09-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_transaksi_status_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='ongkir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ongkos Kirim'),
        ),
        migrations.AlterField(
            model_name='diskonpelanggan',
            name='persen_diskon',
            field=models.IntegerField(verbose_name='Persen Diskon'),
        ),
    ]
