# Generated by Django 4.2 on 2025-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_transaksi_ongkir_alter_diskonpelanggan_persen_diskon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='waktu_checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='batas_waktu_bayar',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]