# Generated by Django 4.2 on 2025-10-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_transaksi_waktu_checkout_transaksi_batas_waktu_bayar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
