# Generated by Django 4.2 on 2025-10-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_pelanggan_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='link_cta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link CTA'),
        ),
    ]
