# Generated by Django 4.2 on 2025-10-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_notifikasi_link_cta'),
    ]

    operations = [
    ]
