# Generated by Django 4.2 on 2025-10-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_auto_20251023_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='target_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Target'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='birthday_discount_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Berakhir Diskon Ulang Tahun'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='total_spending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Belanja Akumulatif'),
        ),
    ]
